### ISSUE TITLE
mark_regex not working

### ISSUE THREAD

**Issue by TimTeaFan** [JohnCoene/marker#1]
The marker add-on for shiny is great. All works fine, but somehow I don't get the `mark_regex()` function to work. Below I changed `input$text2` in `marker_demo()` to match regex. I suppose the regex has to be JS syntax regex (for example "/Lorem/" or "/[a-zA-Z]/"), but neither JS nor R syntax regex (such as "Lorem" or "[a-zA-Z]") seem to work. In a non-shiny context (using the [marker.js configurater](https://markjs.io/configurator.html)) the problem does not occur. 

Is this an actual issue or am I doing something wrong?

```
library(shiny)
library(marker)

data(lorem)

ui <- fluidPage(
  use_marker(),
  tags$head(
    tags$style(
      ".red{background-color:#FFB8C3;}
      .blue{background-color:#6ECFEA;}"
    )
  ),
  h2("Marker"),
  br(),
  p("Dynamically highlight text by typing in the text boxes below."),
  br(),
  div(
    class = "container",
    div(
      class = "well",
      id = "text-to-mark",
      lorem
    ),
    fluidRow(
      column(6, textInput("text", "Keywords to highlight in red via `$mark` ")),
      column(
        6, 
        textInput("text2", "Keywords to highlight in blue via `$mark_regex`"),
        p("Number of keywords matched in blue"),
        verbatimTextOutput("marked")
      )
    )
  )
)

server <- function(input, output){
  
  marker <- marker$new("#text-to-mark")
  
  observeEvent(input$text, {
    marker$
      unmark(className = "red")$
      mark(input$text, className = "red", send_marked = TRUE, send_not_matched = TRUE)
  })
  
  observeEvent(input$text2, {
    print(input$text2)
    marker$
      unmark(className = "blue")$
      mark_regex(input$text2, className = "blue") # changed to match regex
  })
  
  output$marked <- renderPrint({
    marker$get_marked()
  })
  
}

shinyApp(ui, server)
```

**Comment by TimTeaFan** [comment]
In the Firefox console I get the following error when running mark_regex():

> TypeError: e.exec is not a function

**Comment by TimTeaFan** [comment]
Updating to mark.js version v9.0.0 didn't help.

**Comment by JohnCoene** [comment]
Whoops. This should be fixed now. Reinstall and re-try your app as-is. Please feel free to re-open if this still does work.

**Comment by TimTeaFan** [comment]
Perfect. Thanks for the fast response, it now works like a charm.
