### ISSUE TITLE
Highlighting not fully work for rendered UI

### ISSUE THREAD

**Issue by obenno** [JohnCoene/marker#3]
Hi,

Thanks a lot for the marker package. 

I'm a shiny user but not familiar with javascript. And marker is just the one that helps me out. However, I tested with marker package in the code below, it seems the the function will not work everytime on rendered UI. Could you please provide some hints on how to solve this problem? Thanks.

```r
library(shiny)
library(marker)
library(shinydashboard)

data(lorem, package = "marker")

ui <- dashboardPage(
    dashboardHeader(),
    dashboardSidebar(),
    dashboardBody(
        use_marker(),
        fluidPage(
            h2("Test app"),
            tags$head(
                     tags$style(
                              ".red{background-color:#FFB8C3;}.blue{background-color:#6ECFEA;}"
                          )
                 ),

            actionButton("go", "GO"),
            actionButton("reset", "Reset"),
            textInput("text1", "Input DNA sequence"),
            textInput("text2", "text to highlight"),
            fluidRow(
                div(id="text-to-mark",
                    uiOutput("dui")
                    )
            )
        )
    )
)
server <- function(input, output, session){

    ##session$reload()
    marker <- marker$new("#text-to-mark")

    observeEvent(input$reset,{
        session$reload()
    })

    seqTab <- eventReactive(input$go, {
        tabBox(title = "Lorem",
               tabPanel("tab1", p(id = "fake-text", input$text1))
               )
    })

    output$dui <- renderUI({
        seqTab()
    })

    observe({
      seqTab()
      marker$
         unmark(className = "red")$
         mark("ATGC", className = "red")

    })
    observeEvent(input$text2, {
        marker$
            unmark(className = "blue")$ # unmark blue class
            mark(input$text2, className = "blue") # add blue class
    })
}

shinyApp(ui, server)
```

**Comment by alipphardt** [comment]
I also recently encountered this issue and found that using the **delay** parameter for the mark function provides enough time any HTML on the screen to render properly. Without it, the marker functions will trigger immediately and won't work consistently. For the app that I created, I set a delay of 2000 milliseconds.

**Comment by obenno** [comment]
Hi @alipphardt,

Thanks a lot for the hints, that's really helpful!

obenno

**Comment by JohnCoene** [comment]
Sorry for not responding. The issue is probably that the highlight with {marker} happens before the UI element is rendered, using the delay as @alipphardt indicates should help ensure that the highlighting only runs once the UI element to highlight is drawn.

**Comment by alipphardt** [comment]
Is the delay parameter supported by the mark_regex function? I couldn't get it to work properly

**Comment by JohnCoene** [comment]
The `delay` parameter is in the `mark` method.

```r
library(shiny)
library(marker)
library(shinydashboard)

# define delay
DELAY = 500L

data(lorem, package = "marker")

ui <- dashboardPage(
    dashboardHeader(),
    dashboardSidebar(),
    dashboardBody(
        use_marker(),
        fluidPage(
            h2("Test app"),
            tags$head(
                     tags$style(
                              ".red{background-color:#FFB8C3;}.blue{background-color:#6ECFEA;}"
                          )
                 ),

            actionButton("go", "GO"),
            actionButton("reset", "Reset"),
            textInput("text1", "Input DNA sequence"),
            fluidRow(
                div(id="text-to-mark",
                    uiOutput("dui")
                    )
            )
        )
    )
)
server <- function(input, output, session){

    ##session$reload()
    marker <- marker$new("#text-to-mark")

    observeEvent(input$reset,{
        session$reload()
    })

    seqTab <- eventReactive(input$go, {
        tabBox(title = "Lorem",
               tabPanel("tab1", p(id = "fake-text", input$text1))
               )
    })

    output$dui <- renderUI({
        seqTab()
    })

    observe({
      seqTab()
      marker$
         unmark(className = "red")$
         mark("ATGC", className = "red", delay = DELAY) # use delay

    })
}

shinyApp(ui, server)

```

The "issue" so to speak is that the highlight __and__ the rendering of the text-to-be-highlighted both render when clicking the "Go" button. However, `renderUI` is very computationally costly and actually takes more time to fully execute than the highlight; hence the highlight of the text is execute (in the browser) before the text is actually rendered (in the browser).

**Comment by alipphardt** [comment]
Is it possible to add it into the mark_regex function as well? It didn't seem to accept the delay parameter within that specific function.

**Comment by JohnCoene** [comment]
Just added it

**Comment by pierremorallet** [comment]
I have the same bug for `mark_ranges`. It work perfectly for `mark`. Would it be possible to add this argument delay also in this method?
